name: Deploy FortibOne to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Étape 1 : Copier d'abord dans un dossier temporaire (non protégé)
      - name: Copy files to VPS temp folder
        uses: appleboy/scp-action@v1
        with:
          host: 212.132.99.71
          username: fortibtech
          password: 26baraka
          source: "*"
          target: /tmp/fortibone-backend/

      # Étape 2 : Installer sshpass pour commandes SSH
      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      # Étape 3 : Déploiement avec élévation de privilèges
      - name: Deploy FortibOne with sudo
        env:
          VPS_HOST: 212.132.99.71
          VPS_USER: fortibtech
          VPS_PASSWORD: 26baraka
          WORK_DIR: /var/www/fortibone-backend
        run: |
          echo "Connecting to ${VPS_USER}@${VPS_HOST}..."
          sshpass -p "${VPS_PASSWORD}" ssh -o StrictHostKeyChecking=no ${VPS_USER}@${VPS_HOST} << 'EOF'
            set -e

            echo "Connected to VPS. Running with sudo privileges..."

            # Créer le répertoire si inexistant
            echo "$VPS_PASS" | sudo -S mkdir -p /var/www/fortibone-backend
            echo "$VPS_PASS" | sudo -S chown -R $USER:$USER /tmp/fortibone-backend

            echo "Copying files to final directory..."
            echo "$VPS_PASSWORD" | sudo -S rm -rf /var/www/fortibone-backend/*
            echo "$VPS_PASSWORD" | sudo -S cp -r /tmp/fortibone-backend/* /var/www/fortibone-backend/
            echo "$VPS_PASSWORD" | sudo -S chown -R root:root /var/www/fortibone-backend

            cd /var/www/fortibone-backend

            echo "Stopping existing containers..."
            echo "$VPS_PASSWORD" | sudo -S docker compose down || true

            echo "Building and starting new containers..."
            echo "$VPS_PASSWORD" | sudo -S docker compose build
            echo "$VPS_PASSWORD" | sudo -S docker compose up -d

            echo "Waiting for database to be healthy..."
            sleep 10

            echo "Applying database migrations..."
            echo "$VPS_PASSWORD" | sudo -S docker compose exec api npx prisma migrate deploy

            echo "Seeding database..."
            echo "$VPS_PASSWORD" | sudo -S docker compose exec api npm run seed

            echo "Cleaning temp files..."
            echo "$VPS_PASSWORD" | sudo -S rm -rf /tmp/fortibone-backend

            echo "✅ Deployment finished successfully!"
          EOF
