name: Deploy FortibOne to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest # L'environnement où l'action s'exécute (pas votre VPS)

    steps:
      - uses: actions/checkout@v4
      - name: Copy files via SSH
        uses: appleboy/scp-action@v1
        with:
          host: 212.132.99.71
          username: root
          password: lN2mExJY
          source: "*"
          target: /var/www/fortibone-backend/
      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Deploy FortibOne to VPS
        env:
          VPS_HOST: 212.132.99.71
          VPS_USER: root
          WORK_DIR: /var/www/fortibone-backend/
        run: |
          echo "Connecting to ${VPS_USER}@${VPS_HOST}..." 

          sshpass -p "lN2mExJY" ssh -o StrictHostKeyChecking=no root@212.132.99.71 << 'EOF'
            set -e
            echo "Connected to VPS. Current directory: $(pwd)"
            
            cd /var/www/fortibone-backend/
            echo "Changed to directory: $(pwd)"

            echo "Stopping existing containers..."
            docker compose down

            echo "Building and starting new containers..."
            docker compose up -d --build

            echo "Waiting for database to be healthy..."
            sleep 15

            echo "Applying database migrations..."
            docker compose exec api npx prisma migrate deploy

            echo "Seeding database (optional)..."
            docker compose exec api npx prisma db seed

            echo "Deployment finished!"
          EOF
