name: Deploy FortibOne to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest # L'environnement où l'action s'exécute (pas votre VPS)

    steps:
      - uses: actions/checkout@v4
      - name: Copy files via SSH
        uses: appleboy/scp-action@v1
        with:
          host: 51.91.79.101
          username: ubuntu
          password: fortibtech
          source: "*"
          target: /var/www/fortibone-backend/
      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Deploy FortibOne to VPS
        env:
          VPS_HOST: 51.91.79.101
          VPS_USER: ubuntu
          WORK_DIR: /var/www/fortibone-backend/
        run: |
          echo "Connecting to ${VPS_USER}@${VPS_HOST}..." 

          sshpass -p "fortibtech" ssh -o StrictHostKeyChecking=no ubuntu@51.91.79.101 << 'EOF'
            echo "Connected to VPS. Current directory: $(pwd)"
            
            cd /var/www/fortibone-backend/
            echo "Changed to directory: $(pwd)"

            echo "Stopping existing containers..."
            docker compose down

            echo "Building and starting new containers..."
            docker compose build
            docker compose up -d

            echo "Waiting for database to be healthy..."
            sleep 10

            echo "Applying database migrations..."
            docker compose exec api npx prisma migrate deploy

            echo "Seeding database..."
            docker compose exec api npm run seed

            echo "Deployment finished!"
          EOF
